name: Figma Publish
on: workflow_dispatch

concurrency: publish

jobs:
  release:  
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch digital.sbb.ch build
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.actions.createDispatchEvent({
              owner: context.repo.owner,
              repo: 'digital.sbb.ch',
              event_type: 'build-and-deploy',
          })