name: Dummy
on: 
  push: {}
  workflow_dispatch: {}

concurrency: publish

permissions: read-all

jobs:
  release:  
    runs-on: ubuntu-latest
    steps:
    - name: Dispatch digital.sbb.ch build
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.DISPATCH_TOKEN }}
        script: |
          await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: 'digital.sbb.ch',
              event_type: 'build-and-deploy',
          })