name: Release from main branch
on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    if: >
      (
        startsWith(github.event.head_commit.message, 'feat') ||
        startsWith(github.event.head_commit.message, 'fix') ||
        startsWith(github.event.head_commit.message, 'refactor') ||
        contains(github.event.head_commit.message, '!release')
      )
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          scope: sbb-esta
      - name: 'Yarn: Install dependencies'
        run: yarn install --frozen-lockfile --non-interactive
      - name: 'Release: Set git user'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
      - name: 'Release: Create release with commit-and-tag-version'
        run: yarn commit-and-tag-version
      - name: 'Release: Push release to repository'
        run: git push --follow-tags origin main
        
      - name: Publish
        uses: ./.github/actions/publish
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          aws-access-key-id: ${{ secrets.ICON_CDN_AWS_ACCESS_ID }}
          aws-secret-access-key: ${{ secrets.ICON_CDN_AWS_ACCESS_KEY }}
          github-token: ${{ secrets.DISPATCH_TOKEN }}
